travis:
  secure:
    BINSTAR_TOKEN: T/DRvvAnHgqCni4zUGMU90EwH4SxBllqXeC2atC8A0uckUDXeqf0a9Syu627j9Nkb3Ti9uIGrRAzWNzlHBhT/1qXZaJSQ+pZ+Uc8yyTYf+DTuA/glLHkZeHKm/dfPeJP2GoGqFD0IqbO647EHblSdS1gCCMzs+Q8ri8YwD0SbxA8FKOk5alYVkOd0QVZeK3j+I0KZnzSV+jILr/CzlQg+u8wqt7QeyTcE+2KcsGthM7hAJ7dJH6yAwZ43dNb5RunYcpFpCakxS5q/UHPb19a0PuWO29iX/FGrj24W6wp1vqzMJgt+iCS2Mtg4IRugN/n9OCVwe/t0RLGujubpxE/PG5Clg2SHZA4i5Wi3pmLittLHg3GgmzeYHNuWDyzAwYDBO3xf457g8ghJTovLnT8T2wBmxmzCZAwgRc2juLZXSpaCPkHt6Jgm7SsNEWCECw5IWuLdPk7sYBSFzRAQW0QDjES1nUnt9Hrcb5c6V9lYTH5xwYe60ZDFxQPTVV6IaFxQqXARQEsDm5NngE4t5kAfAGqo8cpR38owbtRy/C7Gx3UT+BPGWo5d3wOlADEQ/fWawtOI1pki9Am18O7QFEJ3Qpymh5hw1r+aRrkFzwuyQfOEKpq2NDvEt4yi0AKj6jK6IKGkMSEkClr6hzZBEb1qwcJXidweHkF5/QdjMuAMx0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
